int32 action

int32 ACTION_ENABLE = 1
int32 ACTION_START_HOMING = 2
---
int32 error_code

int32 SUCCESSFUL = 0
int32 ERROR_HOMING_DONE = -1
int32 ERROR_HOMING_IN_PROGRESS = -2
int32 ERROR_NO_COMMUNICATION = -3
int32 ERROR_ALREADY_ENABLED = -4
int32 ERROR_UNKNOWN = -5
---

